### ISSUE TITLE
The Google Cloud Drive where the dataset is stored seems to be disabled

### ISSUE THREAD

**Issue by luoluoluooo** [fawnliu/VGSD#1]

**Comment by fawnliu** [comment]
Hi, @luoluoluooo. Sorry for the inconvenience. I updated the dataset file using the same [Google Drive link](https://drive.google.com/drive/folders/1QsdYI5Gwi-rKKwGgdE7GFTjhRO4-wIiI?usp=sharing), which includes two tar files (train.tar and test.tar). Please do not hesitate to contact me if you have any other questions.

**Comment by luoluoluooo** [comment]
Thanks!
